airtable_base_id  = "appeRwoAIzrNeKwDr"
airtable_table_name = "tblN1FY4esFqClydq"
channel="G01DBHPLK25"
leading_help_text = "To file a report, just DM this bot with your report. You'll be asked to select if you want your report to be anonymous or not"
app_name = "shroud" # If this isn't sppecified, the default is "shroud" meaning the command would be "/shroud-..."

[development]
airtable_table_name = "tbllFyDNwnXlTCMVl"
app_name = "dev-shroud"
airtable_base_id  = "apphYndkize7YybCs"

