import os
import queue
import threading
from typing import Any, cast

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool, PoolTimeout
from pyairtable import Api, Table
from pyairtable.formulas import match

from shroud import settings


class BackendUnavailable(Exception):
    pass


FIELD_COLUMNS = (
    "dm_ts",
    "dm_channel",
    "forwarded_ts",
    "selection_ts",
    "selection",
    "content",
    "reply_time",
    "resolve_time",
    "merged",
    "is_auto_forward",
)

_OMIT_WHEN_FALSE = ("merged", "is_auto_forward")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS reports (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dm_ts              text UNIQUE NOT NULL,
    dm_channel         text NOT NULL,
    forwarded_ts       text,
    selection_ts       text,
    selection          text,
    content            text,
    reply_time         integer,
    resolve_time       integer,
    merged             boolean NOT NULL DEFAULT false,
    is_auto_forward    boolean NOT NULL DEFAULT false,
    legacy_airtable_id text UNIQUE,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS reports_forwarded_ts_idx ON reports (forwarded_ts);
CREATE INDEX IF NOT EXISTS reports_selection_ts_idx ON reports (selection_ts);
ALTER TABLE reports ADD COLUMN IF NOT EXISTS is_auto_forward boolean NOT NULL DEFAULT false;
"""

_pool: ConnectionPool | None = None
_airtable: Table | None = None


def _dsn() -> str:
    dsn = os.environ.get("DATABASE_URL") or settings.get("database_url")
    if not dsn:
        raise RuntimeError("No database configured: set DATABASE_URL or database_url")
    return str(dsn)


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            conninfo=_dsn(),
            min_size=1,
            max_size=10,
            kwargs={"row_factory": dict_row, "autocommit": False},
        )
    return _pool


def _execute(
    query: str, params: Any = (), *, fetch: str | None = None
) -> Any:
    pool = _get_pool()
    try:
        with pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(query, params)
                if fetch == "one":
                    return cur.fetchone()
                if fetch == "all":
                    return cur.fetchall()
                return None
    except (psycopg.OperationalError, PoolTimeout) as e:
        raise BackendUnavailable(str(e)) from e


def _to_record(row: dict[str, Any]) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    for col in FIELD_COLUMNS:
        val = row.get(col)
        if val is None:
            continue
        if col in _OMIT_WHEN_FALSE and not val:
            continue
        fields[col] = val
    return {"id": str(row["id"]), "fields": fields}


def _get_airtable() -> Table | None:
    global _airtable
    if _airtable is not None:
        return _airtable
    token = settings.get("airtable_token")
    base = settings.get("airtable_base_id")
    table_name = settings.get("airtable_table_name")
    if not (token and base and table_name):
        return None
    _airtable = Api(api_key=token, timeout=(5, 15)).table(base, table_name)
    return _airtable


def _airtable_fallback(ts: str) -> dict[str, Any] | None:
    if not settings.get("airtable_fallback", True):
        return None
    table = _get_airtable()
    if table is None:
        return None
    try:
        rec = table.first(
            formula=match(
                {"dm_ts": ts, "forwarded_ts": ts, "selection_ts": ts},
                match_any=True,
            )
        )
    except Exception as e:
        print(f"WARN: Airtable fallback lookup failed (ignored): {e}")
        return None
    if rec is None:
        return None
    return _heal_from_airtable(rec)


def _heal_from_airtable(rec: dict[str, Any]) -> dict[str, Any] | None:
    f = rec.get("fields", {})
    if not f.get("dm_ts") or not f.get("dm_channel"):
        return None
    row = _execute(
        """
        INSERT INTO reports
            (dm_ts, dm_channel, forwarded_ts, selection_ts, selection,
             content, reply_time, resolve_time, merged, legacy_airtable_id)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (dm_ts) DO UPDATE SET legacy_airtable_id = EXCLUDED.legacy_airtable_id
        RETURNING *
        """,
        (
            f.get("dm_ts"),
            f.get("dm_channel"),
            f.get("forwarded_ts"),
            f.get("selection_ts"),
            f.get("selection"),
            f.get("content"),
            f.get("reply_time"),
            f.get("resolve_time"),
            bool(f.get("merged", False)),
            rec["id"],
        ),
        fetch="one",
    )
    print(f"INFO: healed Airtable record {rec['id']} into Postgres as {row['id']}")
    return _to_record(cast(dict[str, Any], row))


def get_message_by_ts(ts: str) -> dict[str, Any] | None:
    row = _execute(
        "SELECT * FROM reports "
        "WHERE dm_ts = %s OR forwarded_ts = %s OR selection_ts = %s "
        "ORDER BY id LIMIT 1",
        (ts, ts, ts),
        fetch="one",
    )
    if row:
        return _to_record(cast(dict[str, Any], row))
    return _airtable_fallback(ts)


def save_forward_start(
    content: str,
    dm_ts: str,
    dm_channel: str,
    selection_ts: str = "",
    is_auto_forward: bool = False,
    selection: str = "",
) -> None:
    row = _execute(
        """
        INSERT INTO reports (dm_ts, content, dm_channel, selection_ts, is_auto_forward, selection)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (dm_ts) DO UPDATE SET
            content = EXCLUDED.content,
            dm_channel = EXCLUDED.dm_channel,
            selection_ts = COALESCE(EXCLUDED.selection_ts, reports.selection_ts),
            is_auto_forward = EXCLUDED.is_auto_forward,
            selection = COALESCE(EXCLUDED.selection, reports.selection),
            updated_at = now()
        RETURNING id
        """,
        (dm_ts, content, dm_channel, selection_ts or None, is_auto_forward, selection or None),
        fetch="one",
    )
    if row:
        _enqueue_mirror("upsert", str(row["id"]))


def finish_forward(dm_ts: str, forwarded_ts: str) -> None:
    row = _execute(
        "UPDATE reports SET forwarded_ts = %s, selection = NULL, updated_at = now() "
        "WHERE dm_ts = %s RETURNING id",
        (forwarded_ts, dm_ts),
        fetch="one",
    )
    if row is None:
        raise ValueError(f"Record with timestamp {dm_ts} not found")
    _enqueue_mirror("upsert", str(row["id"]))


def save_selection(selection_ts: str, selection: str) -> None:
    row = _execute(
        "UPDATE reports SET selection = %s, updated_at = now() "
        "WHERE selection_ts = %s RETURNING id",
        (selection, selection_ts),
        fetch="one",
    )
    if row is None:
        raise ValueError(f"Record with timestamp {selection_ts} not found")
    _enqueue_mirror("upsert", str(row["id"]))


def update_fields(record_id: str, fields: dict[str, Any]) -> None:
    cols = [c for c in fields if c in FIELD_COLUMNS]
    if not cols:
        return
    assignments = ", ".join(f"{c} = %s" for c in cols) + ", updated_at = now()"
    params = [fields[c] for c in cols] + [int(record_id)]
    _execute(f"UPDATE reports SET {assignments} WHERE id = %s", params)
    _enqueue_mirror("upsert", str(record_id))


def delete_record(record_id: str) -> None:
    row = _execute(
        "SELECT legacy_airtable_id FROM reports WHERE id = %s",
        (int(record_id),),
        fetch="one",
    )
    _execute("DELETE FROM reports WHERE id = %s", (int(record_id),))
    if row and row.get("legacy_airtable_id"):
        _enqueue_mirror("delete", row["legacy_airtable_id"])


def query_unresolved(cutoff_ts: str | None = None) -> list[dict[str, Any]]:
    query = (
        "SELECT * FROM reports "
        "WHERE resolve_time IS NULL AND merged = false "
        "AND forwarded_ts IS NOT NULL AND forwarded_ts <> ''"
    )
    params: list[Any] = []
    if cutoff_ts is not None:
        query += " AND forwarded_ts >= %s"
        params.append(cutoff_ts)
    rows = _execute(query, params, fetch="all") or []
    return [_to_record(cast(dict[str, Any], r)) for r in rows]


def clean_database(client) -> None:
    from shroud.utils import utils

    rows = _execute("SELECT * FROM reports", fetch="all") or []
    for row in rows:
        record = _to_record(cast(dict[str, Any], row))
        r = record["fields"]
        messages: list[dict[str, Any]] = []
        try:
            resp1 = client.conversations_history(
                channel=r["dm_channel"], inclusive=True, oldest=r["dm_ts"], limit=1
            )
            data1 = cast(dict[str, Any], resp1.data)
            messages.extend(cast(list[dict[str, Any]], data1.get("messages", [])))
        except KeyError:
            delete_record(record["id"])
            continue
        except Exception:
            continue

        fwd_ts = r.get("forwarded_ts")
        if fwd_ts:
            for channel in utils.report_thread_channels():
                try:
                    resp = client.conversations_history(
                        channel=channel,
                        oldest=fwd_ts,
                        latest=fwd_ts,
                        inclusive=True,
                        limit=1,
                    )
                    msgs = cast(
                        list[dict[str, Any]],
                        cast(dict[str, Any], resp.data).get("messages", []),
                    )
                    if msgs:
                        messages.append(msgs[0])
                        break
                except Exception:
                    pass

        if len(messages) < 2:
            delete_record(record["id"])
            continue

        for m in messages:
            if m.get("subtype") == "tombstone":
                delete_record(record["id"])
                break


AIRTABLE_MIRROR_FIELDS = (
    "dm_ts",
    "dm_channel",
    "forwarded_ts",
    "selection_ts",
    "selection",
    "content",
    "reply_time",
    "resolve_time",
    "merged",
)

_mirror_queue: "queue.Queue[tuple[str, str]]" = queue.Queue()
_mirror_thread: threading.Thread | None = None
_mirror_lock = threading.Lock()


def _mirror_enabled() -> bool:
    return bool(settings.get("airtable_mirror", True)) and _get_airtable() is not None


def _do_mirror_upsert(record_id: str) -> None:
    table = _get_airtable()
    if table is None:
        return
    row = _execute(
        "SELECT * FROM reports WHERE id = %s", (int(record_id),), fetch="one"
    )
    if row is None:
        return
    fields = {k: row.get(k) for k in AIRTABLE_MIRROR_FIELDS}
    air_id = row.get("legacy_airtable_id")
    if air_id:
        table.update(air_id, fields, typecast=True)
    else:
        created = table.create(
            {k: v for k, v in fields.items() if v is not None}, typecast=True
        )
        _execute(
            "UPDATE reports SET legacy_airtable_id = %s WHERE id = %s",
            (created["id"], int(record_id)),
        )


def _do_mirror_delete(air_id: str) -> None:
    table = _get_airtable()
    if table is None or not air_id:
        return
    table.delete(air_id)


def _mirror_worker() -> None:
    while True:
        kind, payload = _mirror_queue.get()
        try:
            if kind == "upsert":
                _do_mirror_upsert(payload)
            elif kind == "delete":
                _do_mirror_delete(payload)
        except Exception as e:
            print(f"WARN: Airtable mirror {kind} for {payload} failed (ignored): {e}")
        finally:
            _mirror_queue.task_done()


def _enqueue_mirror(kind: str, payload: str) -> None:
    if not payload or not _mirror_enabled():
        return
    global _mirror_thread
    if _mirror_thread is None:
        with _mirror_lock:
            if _mirror_thread is None:
                _mirror_thread = threading.Thread(
                    target=_mirror_worker, name="airtable-mirror", daemon=True
                )
                _mirror_thread.start()
    _mirror_queue.put((kind, payload))


def init_schema() -> None:
    pool = _get_pool()
    try:
        with pool.connection() as conn:
            for stmt in _SCHEMA.split(";"):
                if stmt.strip():
                    conn.execute(stmt)
    except (psycopg.OperationalError, PoolTimeout) as e:
        raise BackendUnavailable(str(e)) from e


def main():
    init_schema()


main()
